-- =====================================================
-- SCRIPT COMPLETO DE CREACIÓN DE BASE DE DATOS
-- Sistema de Gestión Médica POO con PHP
-- =====================================================
-- DATABASE: pooconphp
-- VERSION: 1.0
-- FECHA: 2026-02-08
-- =====================================================

-- =====================================================
-- 1. TABLAS DE AUTENTICACIÓN Y USUARIOS
-- =====================================================

-- Tabla de Usuarios del Sistema
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('admin', 'medico', 'cajero')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    active BOOLEAN DEFAULT true
);

-- Tabla de Permisos de Usuario
CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    permission_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, permission_name)
);

-- =====================================================
-- 2. TABLAS DE PACIENTES Y CITAS
-- =====================================================

-- Tabla de Pacientes
CREATE TABLE IF NOT EXISTS pacientes (
    id_paciente SERIAL PRIMARY KEY,
    documento_id VARCHAR(20) UNIQUE NOT NULL,
    primer_nombre VARCHAR(50) NOT NULL,
    segundo_nombre VARCHAR(50),
    primer_apellido VARCHAR(50) NOT NULL,
    segundo_apellido VARCHAR(50),
    fecha_nacimiento DATE,
    telefono VARCHAR(15),
    email VARCHAR(100),
    direccion TEXT,
    barrio VARCHAR(100),
    municipio VARCHAR(100),
    estrato INTEGER CHECK (estrato BETWEEN 1 AND 6),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Citas Médicas
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    duracion_minutos INTEGER DEFAULT 30,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'atendida', 'cancelada')),
    motivo_consulta TEXT,
    motivo_cancelacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 3. TABLAS MÉDICAS (CONSULTAS E HISTORIAS)
-- =====================================================

-- Tabla de Consultas
CREATE TABLE IF NOT EXISTS consultas (
    id_consulta SERIAL PRIMARY KEY,
    id_paciente INTEGER REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    motivo_consulta TEXT,
    enfermedad_actual TEXT,
    medico_id INTEGER REFERENCES users(id),
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'en_proceso', 'finalizada')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Historias Clínicas
CREATE TABLE IF NOT EXISTS historias_clinicas (
    id_historia SERIAL PRIMARY KEY,
    id_paciente INTEGER REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    id_consulta INTEGER REFERENCES consultas(id_consulta) ON DELETE SET NULL,
    fecha_ingreso TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_egreso TIMESTAMP WITH TIME ZONE,
    motivo_consulta TEXT,
    enfermedad_actual TEXT,
    analisis_plan TEXT,
    diagnostico TEXT,
    tratamiento TEXT,
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Signos Vitales
CREATE TABLE IF NOT EXISTS signos_vitales (
    id SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    ta VARCHAR(20),
    pulso INTEGER,
    f_res INTEGER,
    temperatura DECIMAL(4,1),
    peso DECIMAL(5,2),
    talla INTEGER,
    sp02 INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 4. TABLAS DE FÓRMULAS MÉDICAS Y PROCEDIMIENTOS
-- =====================================================

-- Tabla de Medicamentos (Catálogo)
CREATE TABLE IF NOT EXISTS medicamentos (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    principio_activo VARCHAR(200),
    presentacion VARCHAR(100),
    concentracion VARCHAR(50),
    laboratorio VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Fórmulas Médicas
CREATE TABLE IF NOT EXISTS formulas_medicas (
    id_formula SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    medicamento_id INTEGER REFERENCES medicamentos(id),
    dosis VARCHAR(100),
    cantidad INTEGER,
    frecuencia VARCHAR(100),
    duracion VARCHAR(100),
    via_administracion VARCHAR(50),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Procedimientos
CREATE TABLE IF NOT EXISTS procedimientos (
    id SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    procedimiento VARCHAR(200),
    descripcion TEXT,
    codigo VARCHAR(20),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 5. TABLAS DE DATOS DE REFERENCIA (CIE-10, CUPS)
-- =====================================================

-- Tabla CIE-10 (Diagnósticos)
CREATE TABLE IF NOT EXISTS cie10 (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(10) UNIQUE NOT NULL,
    descripcion TEXT NOT NULL,
    categoria VARCHAR(100)
);

-- Tabla CUPS (Procedimientos)
CREATE TABLE IF NOT EXISTS cups (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(20) UNIQUE NOT NULL,
    descripcion TEXT NOT NULL,
    categoria VARCHAR(100)
);

-- =====================================================
-- 6. TABLAS DE FACTURACIÓN
-- =====================================================

-- Tabla de Facturas
CREATE TABLE IF NOT EXISTS facturas (
    id_factura SERIAL PRIMARY KEY,
    id_paciente INTEGER REFERENCES pacientes(id_paciente),
    id_consulta INTEGER REFERENCES consultas(id_consulta),
    numero_factura VARCHAR(50) UNIQUE,
    fecha_emision TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    subtotal DECIMAL(12,2) DEFAULT 0,
    descuento DECIMAL(12,2) DEFAULT 0,
    iva DECIMAL(12,2) DEFAULT 0,
    total DECIMAL(12,2) DEFAULT 0,
    estado VARCHAR(20) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'pagada', 'anulada')),
    metodo_pago VARCHAR(50),
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Ítems de Factura
CREATE TABLE IF NOT EXISTS factura_items (
    id SERIAL PRIMARY KEY,
    id_factura INTEGER REFERENCES facturas(id_factura) ON DELETE CASCADE,
    descripcion VARCHAR(200) NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_unitario DECIMAL(12,2) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Pagos
CREATE TABLE IF NOT EXISTS pagos (
    id_pago SERIAL PRIMARY KEY,
    id_factura INTEGER REFERENCES facturas(id_factura) ON DELETE CASCADE,
    fecha_pago TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    monto DECIMAL(12,2) NOT NULL,
    metodo_pago VARCHAR(50),
    referencia VARCHAR(100),
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 7. TABLAS DE MÉDICOS Y CONFIGURACIÓN
-- =====================================================

-- Tabla de Médicos (Perfiles extendidos)
CREATE TABLE IF NOT EXISTS medicos (
    id SERIAL PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    especialidad VARCHAR(100),
    registro_medico VARCHAR(50),
    telefono VARCHAR(15),
    email VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Configuración del Sistema
CREATE TABLE IF NOT EXISTS configuracion (
    id SERIAL PRIMARY KEY,
    clave VARCHAR(100) UNIQUE NOT NULL,
    valor TEXT,
    descripcion TEXT,
    tipo VARCHAR(20) DEFAULT 'texto',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 8. TABLA DE SINCRONIZACIÓN
-- =====================================================

CREATE TABLE IF NOT EXISTS sync_logs (
    id SERIAL PRIMARY KEY,
    tabla VARCHAR(100) NOT NULL,
    accion VARCHAR(20) NOT NULL,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    usuario_id INTEGER REFERENCES users(id),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sincronizado BOOLEAN DEFAULT false
);

-- =====================================================
-- 9. ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

-- Índices de Pacientes
CREATE INDEX IF NOT EXISTS idx_pacientes_documento ON pacientes(documento_id);
CREATE INDEX IF NOT EXISTS idx_pacientes_nombre ON pacientes(primer_nombre, primer_apellido);

-- Índices de Citas
CREATE INDEX IF NOT EXISTS idx_citas_paciente ON citas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_citas_medico ON citas(medico_id);
CREATE INDEX IF NOT EXISTS idx_citas_fecha ON citas(fecha_hora);
CREATE INDEX IF NOT EXISTS idx_citas_estado ON citas(estado);

-- Índices de Consultas
CREATE INDEX IF NOT EXISTS idx_consultas_paciente ON consultas(id_paciente);
CREATE INDEX IF NOT EXISTS idx_consultas_medico ON consultas(medico_id);
CREATE INDEX IF NOT EXISTS idx_consultas_estado ON consultas(estado);

-- Índices de Historias
CREATE INDEX IF NOT EXISTS idx_historias_paciente ON historias_clinicas(id_paciente);
CREATE INDEX IF NOT EXISTS idx_historias_consulta ON historias_clinicas(id_consulta);
CREATE INDEX IF NOT EXISTS idx_historias_fecha ON historias_clinicas(fecha_ingreso);

-- Índices de Facturas
CREATE INDEX IF NOT EXISTS idx_facturas_paciente ON facturas(id_paciente);
CREATE INDEX IF NOT EXISTS idx_facturas_numero ON facturas(numero_factura);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON facturas(estado);

-- =====================================================
-- 10. ROW LEVEL SECURITY (RLS)
-- =====================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE citas ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultas ENABLE ROW LEVEL SECURITY;
ALTER TABLE historias_clinicas ENABLE ROW LEVEL SECURITY;
ALTER TABLE facturas ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (permitir todo - luego personalizar según necesidades)
CREATE POLICY "Permitir todo en users" ON users FOR ALL USING (true);
CREATE POLICY "Permitir todo en pacientes" ON pacientes FOR ALL USING (true);
CREATE POLICY "Permitir todo en citas" ON citas FOR ALL USING (true);
CREATE POLICY "Permitir todo en consultas" ON consultas FOR ALL USING (true);
CREATE POLICY "Permitir todo en historias" ON historias_clinicas FOR ALL USING (true);
CREATE POLICY "Permitir todo en facturas" ON facturas FOR ALL USING (true);

-- =====================================================
-- 11. DATOS INICIALES
-- =====================================================

-- Usuario Admin por defecto
INSERT INTO users (username, password_hash, nombre_completo, rol) 
VALUES ('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Administrador', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Usuario Médico de prueba
INSERT INTO users (username, password_hash, nombre_completo, rol) 
VALUES ('medico', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Médico de Prueba', 'medico')
ON CONFLICT (username) DO NOTHING;

-- Usuario Cajero de prueba
INSERT INTO users (username, password_hash, nombre_completo, rol) 
VALUES ('cajero', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Cajero de Prueba', 'cajero')
ON CONFLICT (username) DO NOTHING;

-- Configuración inicial
INSERT INTO configuracion (clave, valor, descripcion, tipo) VALUES
('nombre_institucion', 'Centro Médico', 'Nombre de la institución médica', 'texto'),
('nit', '900123456-1', 'NIT de la institución', 'texto'),
('direccion', 'Calle 123 # 45-67', 'Dirección de la institución', 'texto'),
('telefono', '3001234567', 'Teléfono de contacto', 'texto'),
('email', 'info@centromedico.com', 'Email de contacto', 'email'),
('valor_consulta', '50000', 'Valor base consulta médica', 'numero'),
('iva_porcentaje', '0', 'Porcentaje de IVA aplicable', 'numero')
ON CONFLICT (clave) DO NOTHING;

-- =====================================================
-- FIN DEL SCRIPT
-- =====================================================

-- Nota: Las contraseñas por defecto son 'password'
-- Se recomienda cambiarlas inmediatamente después de la instalación
