-- Tabla de Usuarios del Sistema
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('admin', 'medico', 'cajero')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    active BOOLEAN DEFAULT true
);

-- Tabla de Citas Médicas
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES users(id) ON DELETE SET NULL, -- Si se borra el médico, la cita queda huérfana pero visible
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    duracion_minutos INTEGER DEFAULT 30,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'atendida', 'cancelada')),
    motivo_consulta TEXT,
    motivo_cancelacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_citas_paciente ON citas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_citas_medico ON citas(medico_id);
CREATE INDEX IF NOT EXISTS idx_citas_fecha ON citas(fecha_hora);

-- Políticas RLS (Row Level Security) - Opcional pero recomendado
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE citas ENABLE ROW LEVEL SECURITY;

-- Permitir todo por ahora (luego se puede restringir según el rol logueado si se usa Auth de Supabase nativo, 
-- pero aquí usaremos nuestra propia lógica PHP, así que la API Key de servicio tendrá acceso total)
CREATE POLICY "Permitir todo en users" ON users FOR ALL USING (true);
CREATE POLICY "Permitir todo en citas" ON citas FOR ALL USING (true);
