-- Restore missing tables logic

-- 1. Users (Auth)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('admin', 'medico', 'cajero')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    active BOOLEAN DEFAULT true
);

-- 2. Especialidades
CREATE TABLE IF NOT EXISTS especialidades (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

-- 3. Medicos
CREATE TABLE IF NOT EXISTS medicos (
    id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    primer_nombre VARCHAR(50) NOT NULL,
    segundo_nombre VARCHAR(50),
    primer_apellido VARCHAR(50) NOT NULL,
    segundo_apellido VARCHAR(50),
    num_documento VARCHAR(20),
    num_registro VARCHAR(50),
    fecha_nacimiento DATE,
    genero VARCHAR(20),
    direccion TEXT,
    especialidad_id INTEGER REFERENCES especialidades(id),
    telefono VARCHAR(20),
    email VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW()
);

-- 4. Consultas (Depends on Pacientes, Users)
-- We assume Pacientes exists (created by crear_tablas.sql)
CREATE TABLE IF NOT EXISTS consultas (
    id_consulta SERIAL PRIMARY KEY,
    id_paciente INTEGER REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    motivo_consulta TEXT,
    enfermedad_actual TEXT,
    estado VARCHAR(20) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'en_proceso', 'finalizada')),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 5. Signos Vitales (Depends on Historias)
CREATE TABLE IF NOT EXISTS signos_vitales (
    id SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    ta VARCHAR(20),
    pulso INTEGER,
    f_res INTEGER,
    temperatura DECIMAL(4,1),
    peso DECIMAL(5,2),
    talla INTEGER,
    sp02 INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 6. Formulas Medicas
CREATE TABLE IF NOT EXISTS medicamentos (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    presentacion VARCHAR(100),
    concentracion VARCHAR(50),
    stock INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS formulas_medicas (
    id_formula SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    medicamento_id INTEGER REFERENCES medicamentos(id),
    dosis VARCHAR(100),
    cantidad INTEGER,
    fecha_hora TIMESTAMP DEFAULT NOW()
);

-- Insertar especialidad por defecto
INSERT INTO especialidades (nombre) VALUES ('Medicina General') ON CONFLICT DO NOTHING;

-- Insert default admin if not exists (hashed 'admin123')
INSERT INTO users (username, password_hash, nombre_completo, rol) 
VALUES ('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Administrador', 'admin')
ON CONFLICT (username) DO NOTHING;
