-- =====================================================
-- SCRIPT COMPLETO DE CREACIÓN DE BASE DE DATOS
-- Sistema de Gestión Médica POO con PHP
-- =====================================================
-- DATABASE: pooconphp
-- VERSION: 1.0
-- FECHA: 2026-02-08
-- =====================================================

-- =====================================================
-- 1. TABLAS DE AUTENTICACIÓN Y USUARIOS
-- =====================================================

-- Tabla de Usuarios del Sistema
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('admin', 'medico', 'cajero')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    active BOOLEAN DEFAULT true
);

-- Tabla de Permisos de Usuario
CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    permission_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, permission_name)
);

-- =====================================================
-- 2. TABLAS DE PACIENTES Y CITAS
-- =====================================================

-- Tabla de Pacientes
CREATE TABLE IF NOT EXISTS pacientes (
    id_paciente SERIAL PRIMARY KEY,
    documento_id VARCHAR(20) UNIQUE NOT NULL,
    primer_nombre VARCHAR(50) NOT NULL,
    segundo_nombre VARCHAR(50),
    primer_apellido VARCHAR(50) NOT NULL,
    segundo_apellido VARCHAR(50),
    fecha_nacimiento DATE,
    telefono VARCHAR(15),
    email VARCHAR(100),
    direccion TEXT,
    barrio VARCHAR(100),
    municipio VARCHAR(100),
    estrato INTEGER CHECK (estrato BETWEEN 1 AND 6),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Citas Médicas
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    duracion_minutos INTEGER DEFAULT 30,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'atendida', 'cancelada')),
    motivo_consulta TEXT,
    motivo_cancelacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 3. TABLAS MÉDICAS (CONSULTAS E HISTORIAS)
-- =====================================================

-- Tabla de Consultas
CREATE TABLE IF NOT EXISTS consultas (
    id_consulta SERIAL PRIMARY KEY,
    id_paciente INTEGER REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    motivo_consulta TEXT,
    enfermedad_actual TEXT,
    medico_id INTEGER REFERENCES users(id),
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'en_proceso', 'finalizada')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Historias Clínicas
CREATE TABLE IF NOT EXISTS historias_clinicas (
    id_historia SERIAL PRIMARY KEY,
    id_paciente INTEGER REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    id_consulta INTEGER REFERENCES consultas(id_consulta) ON DELETE SET NULL,
    fecha_ingreso TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    fecha_egreso TIMESTAMP WITH TIME ZONE,
    motivo_consulta TEXT,
    enfermedad_actual TEXT,
    analisis_plan TEXT,
    diagnostico TEXT,
    tratamiento TEXT,
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Signos Vitales
CREATE TABLE IF NOT EXISTS signos_vitales (
    id SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    ta VARCHAR(20),
    pulso INTEGER,
    f_res INTEGER,
    temperatura DECIMAL(4,1),
    peso DECIMAL(5,2),
    talla INTEGER,
    sp02 INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 4. TABLAS DE FÓRMULAS MÉDICAS Y PROCEDIMIENTOS
-- =====================================================

-- Tabla de Medicamentos (Catálogo)
CREATE TABLE IF NOT EXISTS medicamentos (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    principio_activo VARCHAR(200),
    presentacion VARCHAR(100),
    concentracion VARCHAR(50),
    laboratorio VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Fórmulas Médicas
CREATE TABLE IF NOT EXISTS formulas_medicas (
    id_formula SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    medicamento_id INTEGER REFERENCES medicamentos(id),
    dosis VARCHAR(100),
    cantidad INTEGER,
    frecuencia VARCHAR(100),
    duracion VARCHAR(100),
    via_administracion VARCHAR(50),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Procedimientos
CREATE TABLE IF NOT EXISTS procedimientos (
    id SERIAL PRIMARY KEY,
    id_historia INTEGER REFERENCES historias_clinicas(id_historia) ON DELETE CASCADE,
    procedimiento VARCHAR(200),
    descripcion TEXT,
    codigo VARCHAR(20),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 5. TABLAS DE DATOS DE REFERENCIA (CIE-10, CUPS)
-- =====================================================

-- Tabla CIE-10 (Diagnósticos)
CREATE TABLE IF NOT EXISTS cie10 (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(10) UNIQUE NOT NULL,
    descripcion TEXT NOT NULL,
    categoria VARCHAR(100)
);

-- Tabla CUPS (Procedimientos)
CREATE TABLE IF NOT EXISTS cups (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(20) UNIQUE NOT NULL,
    descripcion TEXT NOT NULL,
    categoria VARCHAR(100)
);

-- =====================================================
-- 6. TABLAS DE FACTURACIÓN
-- =====================================================

-- Tabla de Facturas
CREATE TABLE IF NOT EXISTS facturas (
    id_factura SERIAL PRIMARY KEY,
    id_paciente INTEGER REFERENCES pacientes(id_paciente),
    id_consulta INTEGER REFERENCES consultas(id_consulta),
    numero_factura VARCHAR(50) UNIQUE,
    fecha_emision TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    subtotal DECIMAL(12,2) DEFAULT 0,
    descuento DECIMAL(12,2) DEFAULT 0,
    iva DECIMAL(12,2) DEFAULT 0,
    total DECIMAL(12,2) DEFAULT 0,
    estado VARCHAR(20) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'pagada', 'anulada')),
    metodo_pago VARCHAR(50),
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Ítems de Factura
CREATE TABLE IF NOT EXISTS factura_items (
    id SERIAL PRIMARY KEY,
    id_factura INTEGER REFERENCES facturas(id_factura) ON DELETE CASCADE,
    descripcion VARCHAR(200) NOT NULL,
    cantidad INTEGER NOT NULL DEFAULT 1,
    precio_unitario DECIMAL(12,2) NOT NULL,
    subtotal DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Pagos
CREATE TABLE IF NOT EXISTS pagos (
    id_pago SERIAL PRIMARY KEY,
    id_factura INTEGER REFERENCES facturas(id_factura) ON DELETE CASCADE,
    fecha_pago TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    monto DECIMAL(12,2) NOT NULL,
    metodo_pago VARCHAR(50),
    referencia VARCHAR(100),
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 7. TABLAS DE MÉDICOS Y CONFIGURACIÓN
-- =====================================================

-- Tabla de Médicos (Perfiles extendidos)
CREATE TABLE IF NOT EXISTS medicos (
    id SERIAL PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    especialidad VARCHAR(100),
    registro_medico VARCHAR(50),
    telefono VARCHAR(15),
    email VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Configuración del Sistema
CREATE TABLE IF NOT EXISTS configuracion (
    id SERIAL PRIMARY KEY,
    clave VARCHAR(100) UNIQUE NOT NULL,
    valor TEXT,
    descripcion TEXT,
    tipo VARCHAR(20) DEFAULT 'texto',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 7.5. TABLAS DE DATOS GEOGRÁFICOS (NARIÑO)
-- =====================================================

-- Tabla de Ciudades/Municipios (enfocada en Nariño)
CREATE TABLE IF NOT EXISTS ciudades (
    id SERIAL PRIMARY KEY,
    codigo_dane VARCHAR(10) UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    departamento VARCHAR(50) NOT NULL DEFAULT 'Nariño',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de Barrios (enfocada en Pasto)
CREATE TABLE IF NOT EXISTS barrio (
    id SERIAL PRIMARY KEY,
    ciudad_id INTEGER REFERENCES ciudades(id) ON DELETE CASCADE,
    barrio VARCHAR(150) NOT NULL,
    zona VARCHAR(50), -- Norte, Sur, Centro, Oriente, Occidente
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- 8. TABLA DE SINCRONIZACIÓN
-- =====================================================

CREATE TABLE IF NOT EXISTS sync_logs (
    id SERIAL PRIMARY KEY,
    tabla VARCHAR(100) NOT NULL,
    accion VARCHAR(20) NOT NULL,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    usuario_id INTEGER REFERENCES users(id),
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sincronizado BOOLEAN DEFAULT false
);

-- =====================================================
-- 9. ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

-- Índices de Pacientes
CREATE INDEX IF NOT EXISTS idx_pacientes_documento ON pacientes(documento_id);
CREATE INDEX IF NOT EXISTS idx_pacientes_nombre ON pacientes(primer_nombre, primer_apellido);

-- Índices de Citas
CREATE INDEX IF NOT EXISTS idx_citas_paciente ON citas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_citas_medico ON citas(medico_id);
CREATE INDEX IF NOT EXISTS idx_citas_fecha ON citas(fecha_hora);
CREATE INDEX IF NOT EXISTS idx_citas_estado ON citas(estado);

-- Índices de Consultas
CREATE INDEX IF NOT EXISTS idx_consultas_paciente ON consultas(id_paciente);
CREATE INDEX IF NOT EXISTS idx_consultas_medico ON consultas(medico_id);
CREATE INDEX IF NOT EXISTS idx_consultas_estado ON consultas(estado);

-- Índices de Historias
CREATE INDEX IF NOT EXISTS idx_historias_paciente ON historias_clinicas(id_paciente);
CREATE INDEX IF NOT EXISTS idx_historias_consulta ON historias_clinicas(id_consulta);
CREATE INDEX IF NOT EXISTS idx_historias_fecha ON historias_clinicas(fecha_ingreso);

-- Índices de Facturas
CREATE INDEX IF NOT EXISTS idx_facturas_paciente ON facturas(id_paciente);
CREATE INDEX IF NOT EXISTS idx_facturas_numero ON facturas(numero_factura);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON facturas(estado);

-- Índices de Geografía
CREATE INDEX IF NOT EXISTS idx_ciudades_departamento ON ciudades(departamento);
CREATE INDEX IF NOT EXISTS idx_ciudades_nombre ON ciudades(nombre);
CREATE INDEX IF NOT EXISTS idx_barrio_ciudad ON barrio(ciudad_id);
CREATE INDEX IF NOT EXISTS idx_barrio_zona ON barrio(zona);

-- =====================================================
-- 10. ROW LEVEL SECURITY (RLS)
-- =====================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE citas ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultas ENABLE ROW LEVEL SECURITY;
ALTER TABLE historias_clinicas ENABLE ROW LEVEL SECURITY;
ALTER TABLE facturas ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (permitir todo - luego personalizar según necesidades)
CREATE POLICY "Permitir todo en users" ON users FOR ALL USING (true);
CREATE POLICY "Permitir todo en pacientes" ON pacientes FOR ALL USING (true);
CREATE POLICY "Permitir todo en citas" ON citas FOR ALL USING (true);
CREATE POLICY "Permitir todo en consultas" ON consultas FOR ALL USING (true);
CREATE POLICY "Permitir todo en historias" ON historias_clinicas FOR ALL USING (true);
CREATE POLICY "Permitir todo en facturas" ON facturas FOR ALL USING (true);

-- =====================================================
-- 11. DATOS INICIALES
-- =====================================================

-- Usuario Admin por defecto
INSERT INTO users (username, password_hash, nombre_completo, rol) 
VALUES ('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Administrador', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Usuario Médico de prueba
INSERT INTO users (username, password_hash, nombre_completo, rol) 
VALUES ('medico', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Médico de Prueba', 'medico')
ON CONFLICT (username) DO NOTHING;

-- Usuario Cajero de prueba
INSERT INTO users (username, password_hash, nombre_completo, rol) 
VALUES ('cajero', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Cajero de Prueba', 'cajero')
ON CONFLICT (username) DO NOTHING;

-- Configuración inicial
INSERT INTO configuracion (clave, valor, descripcion, tipo) VALUES
('nombre_institucion', 'Centro Médico', 'Nombre de la institución médica', 'texto'),
('nit', '900123456-1', 'NIT de la institución', 'texto'),
('direccion', 'Calle 123 # 45-67', 'Dirección de la institución', 'texto'),
('telefono', '3001234567', 'Teléfono de contacto', 'texto'),
('email', 'info@centromedico.com', 'Email de contacto', 'email'),
('valor_consulta', '50000', 'Valor base consulta médica', 'numero'),
('iva_porcentaje', '0', 'Porcentaje de IVA aplicable', 'numero')
ON CONFLICT (clave) DO NOTHING;

-- =====================================================
-- FIN DEL SCRIPT
-- =====================================================

-- Nota: Las contraseñas por defecto son 'password'
-- Se recomienda cambiarlas inmediatamente después de la instalación
-- ============================================
-- DATOS DE REFERENCIA
-- Tipos de documento, EPS, ciudades, etc.
-- ============================================

-- Tabla de Tipos de Documento
CREATE TABLE IF NOT EXISTS tipo_documento (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(10) UNIQUE NOT NULL,
    descripcion VARCHAR(100) NOT NULL
);

-- Insertar tipos de documento colombianos
INSERT INTO tipo_documento (codigo, descripcion) VALUES
('CC', 'Cédula de Ciudadanía'),
('TI', 'Tarjeta de Identidad'),
('RC', 'Registro Civil'),
('CE', 'Cédula de Extranjería'),
('PA', 'Pasaporte'),
('MS', 'Menor Sin Identificación'),
('AS', 'Adulto Sin Identificación')
ON CONFLICT (codigo) DO NOTHING;

-- Tabla de EPS
CREATE TABLE IF NOT EXISTS eps (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(20) UNIQUE NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    activa BOOLEAN DEFAULT true
);

-- Insertar EPS principales de Colombia
INSERT INTO eps (codigo, nombre) VALUES
('EPS001', 'Nueva EPS'),
('EPS002', 'Sura EPS'),
('EPS003', 'Sanitas EPS'),
('EPS004', 'Salud Total'),
('EPS005', 'Compensar'),
('EPS006', 'Famisanar'),
('EPS007', 'Aliansalud'),
('EPS008', 'Coosalud'),
('EPS009', 'Mutual Ser'),
('EPS010', 'Cafesalud'),
('EPS011', 'Comfenalco'),
('EPS012', 'Comfandi'),
('EPS013', 'Cruz Blanca'),
('EPS014', 'Medimás'),
('EPS015', 'Capital Salud'),
('EPS016', 'Coomeva'),
('EPS017', 'Emssanar'),
('PART', 'Particular'),
('OTRO', 'Otra EPS')
ON CONFLICT (codigo) DO NOTHING;

-- Comentarios
COMMENT ON TABLE tipo_documento IS 'Tipos de documentos de identificación en Colombia';
COMMENT ON TABLE eps IS 'Entidades Promotoras de Salud en Colombia';
-- =====================================================
-- DATOS GEOGRÁFICOS: NARIÑO - PASTO Y MUNICIPIOS ALEDAÑOS
-- =====================================================
-- Script SQL para poblar tablas de ciudades y barrios
-- Enfocado en el departamento de Nariño, Colombia
-- Con énfasis en Pasto y municipios circundantes
-- =====================================================

-- =====================================================
-- TABLA: CIUDADES / MUNICIPIOS DE NARIÑO
-- =====================================================

CREATE TABLE IF NOT EXISTS ciudades (
    id SERIAL PRIMARY KEY,
    codigo_dane VARCHAR(10) UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    departamento VARCHAR(50) NOT NULL DEFAULT 'Nariño',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- INSERTAR MUNICIPIOS DE NARIÑO
-- Ordenados por importancia: Pasto primero, luego municipios aledaños
INSERT INTO ciudades (codigo_dane, nombre, departamento) VALUES
-- 1. PASTO (Capital departamental)
('52001', 'Pasto (San Juan de Pasto)', 'Nariño'),

-- 2. MUNICIPIOS DEL ÁREA METROPOLITANA Y CERCANOS A PASTO
('52689', 'Sandoná', 'Nariño'),
('52399', 'La Florida', 'Nariño'),
('52678', 'Consacá', 'Nariño'),
('52786', 'Tangua', 'Nariño'),  
('52885', 'Yacuanquer', 'Nariño'),
('52051', 'Buesaco', 'Nariño'),
('52258', 'Funes', 'Nariño'),
('52381', 'La Cruz', 'Nariño'),
('52788', 'Taminango', 'Nariño'),

-- 3. OTROS MUNICIPIOS IMPORTANTES DE NARIÑO
('52835', 'Túquerres', 'Nariño'),
('52083', 'Ipiales', 'Nariño'),
('52480', 'Nariño', 'Nariño'),
('52694', 'Sapuyes', 'Nariño'),
('52287', 'Guaitarilla', 'Nariño'),
('52520', 'Ospina', 'Nariño'),
('52520', 'Pupiales', 'Nariño'),
('52560', 'Piedrancha', 'Nariño'),
('52585', 'Policarpa', 'Nariño'),
('52612', 'Ricaurte', 'Nariño'),
('52696', 'Samaniego', 'Nariño'),
('52786', 'Tumaco (San Andrés de Tumaco)', 'Nariño'),
('52240', 'El Tambo', 'Nariño'),
('52418', 'La Unión', 'Nariño'),
('52405', 'La Llanada', 'Nariño'),
('52207', 'Cumbal', 'Nariño'),
('52233', 'El Charco', 'Nariño'),
('52490', 'Olaya Herrera', 'Nariño')
ON CONFLICT (codigo_dane) DO NOTHING;

-- =====================================================
-- TABLA: BARRIOS DE PASTO
-- =====================================================

CREATE TABLE IF NOT EXISTS barrio (
    id SERIAL PRIMARY KEY,
    ciudad_id INTEGER REFERENCES ciudades(id) ON DELETE CASCADE,
    barrio VARCHAR(150) NOT NULL,
    zona VARCHAR(50), -- Norte, Sur, Centro, Oriente, Occidente
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- INSERTAR BARRIOS DE PASTO
-- Divididos por zonas geográficas de la ciudad

-- ZONA CENTRO
INSERT INTO barrio (ciudad_id, barrio, zona) 
SELECT id, 'Centro', 'Centro' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Panadería', 'Centro' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'San Juan de Dios', 'Centro' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Santiago', 'Centro' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'San Felipe', 'Centro' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Las Cuadras', 'Centro' FROM ciudades WHERE codigo_dane = '52001'

-- ZONA NORTE  
UNION ALL
SELECT id, 'Torobajo', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Jongovito', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Lomita', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'El Progreso', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Aranda', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'San Vicente', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Pullitopamba', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Carolina', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Chimangual', 'Norte' FROM ciudades WHERE codigo_dane = '52001'

-- ZONA SUR
UNION ALL
SELECT id, 'Lorenzo', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Mijitayo', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'El Bosque', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Chambú', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Pandiaco', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Catambuco', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Cujacal', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Obonuco', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'San Francisco', 'Sur' FROM ciudades WHERE codigo_dane = '52001'

-- ZONA ORIENTAL
UNION ALL
SELECT id, 'Chapalito', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Miraflores', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'El Rosario', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Aurora', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'San Andrés', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Esperanza', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'

-- ZONA OCCIDENTAL
UNION ALL
SELECT id, 'Tamasagra', 'Occidente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Isla', 'Occidente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Fátima', 'Occidente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Alameda del Río', 'Occidente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Aguapamba', 'Occidente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Tejar', 'Occidente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Sindagua', 'Occidente' FROM ciudades WHERE codigo_dane = '52001'

-- COMUNAS Y BARRIOS ADICIONALES IMPORTANTES
UNION ALL
SELECT id, 'San Antonio de Padua', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Puerres', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Modelo Centro', 'Centro' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Santa Mónica', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Floresta', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'La Castellana', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Morasurco', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Tescual', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Villa del Prado', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Arboledas', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Las Palmas', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Anganoy', 'Norte' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'Mapachico', 'Sur' FROM ciudades WHERE codigo_dane = '52001'
UNION ALL
SELECT id, 'San Ignacio', 'Oriente' FROM ciudades WHERE codigo_dane = '52001'
ON CONFLICT DO NOTHING;

-- =====================================================
-- ÍNDICES PARA OPTIMIZACIÓN
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_ciudades_departamento ON ciudades(departamento);
CREATE INDEX IF NOT EXISTS idx_ciudades_nombre ON ciudades(nombre);
CREATE INDEX IF NOT EXISTS idx_barrio_ciudad ON barrio(ciudad_id);
CREATE INDEX IF NOT EXISTS idx_barrio_zona ON barrio(zona);

-- =====================================================
-- COMENTARIOS Y NOTAS
-- =====================================================

COMMENT ON TABLE ciudades IS 'Catálogo de municipios de Nariño con énfasis en Pasto y área metropolitana';
COMMENT ON TABLE barrio IS 'Barrios de Pasto organizados por zonas geográficas (Centro, Norte, Sur, Oriente, Occidente)';
COMMENT ON COLUMN barrio.zona IS 'Zona geográfica del barrio dentro de Pasto';

-- =====================================================
-- VERIFICACIÓN
-- =====================================================

-- Ver cantidad de municipios insertados
-- SELECT COUNT(*) as total_municipios FROM ciudades WHERE departamento = 'Nariño';

-- Ver cantidad de barrios de Pasto
-- SELECT COUNT(*) as total_barrios FROM barrio WHERE ciudad_id = (SELECT id FROM ciudades WHERE codigo_dane = '52001');

-- Ver barrios por zona
-- SELECT zona, COUNT(*) as cantidad 
-- FROM barrio b
-- JOIN ciudades c ON b.ciudad_id = c.id
-- WHERE c.codigo_dane = '52001'
-- GROUP BY zona
-- ORDER BY zona;
-- ============================================
-- USUARIOS Y PERFILES
-- ============================================

-- Insertar usuarios del sistema con contraseñas (admin123 para todos)
INSERT INTO users (username, password_hash, nombre_completo, rol, active) VALUES
('admin', '$2y$10$M4OviwdGVsE29dOPm6xq3.yLkN/Q8nB7mQZJ8T1zKxLz2YhGxVJRW', 'Administrador', 'admin', true),
('medico', '$2y$10$M4OviwdGVsE29dOPm6xq3.yLkN/Q8nB7mQZJ8T1zKxLz2YhGxVJRW', 'Médico de Prueba', 'medico', true),
('cajero', '$2y$10$M4OviwdGVsE29dOPm6xq3.yLkN/Q8nB7mQZJ8T1zKxLz2YhGxVJRW', 'Cajero de Prueba', 'cajero', true),
('facturador', '$2y$10$M4OviwdGVsE29dOPm6xq3.yLkN/Q8nB7mQZJ8T1zKxLz2YhGxVJRW', 'Facturador de Prueba', 'cajero', true)
ON CONFLICT (username) DO NOTHING;

-- Crear perfil médico para el usuario medico
INSERT INTO medicos (user_id, especialidad, registro_medico, telefono, email)
SELECT id, 'Medicina General', 'RM-12345', '3001234567', 'medico@example.com'
FROM users 
WHERE username = 'medico'
ON CONFLICT (user_id) DO NOTHING;

-- ============================================
-- VERIFICACIÓN FINAL
-- ============================================

-- Resumen de datos insertados
DO $$
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE 'CONFIGURACIÓN COMPLETADA';
    RAISE NOTICE '========================================';
    RAISE NOTICE '';
    RAISE NOTICE 'Usuarios: %', (SELECT COUNT(*) FROM users);
    RAISE NOTICE 'Perfiles médicos: %', (SELECT COUNT(*) FROM medicos);
    RAISE NOTICE 'Municipios Nariño: %', (SELECT COUNT(*) FROM ciudades WHERE departamento = 'Nariño');
    RAISE NOTICE 'Barrios Pasto: %', (SELECT COUNT(*) FROM barrio b JOIN ciudades c ON b.ciudad_id = c.id WHERE c.codigo_dane = '52001');
    RAISE NOTICE '';
    RAISE NOTICE 'El sistema está listo para usar';
    RAISE NOTICE '========================================';
END $$;
