-- ==========================================
-- SCRIPT DE ACTUALIZACIÓN COMPLETA
-- Copia y pega TODO esto en el SQL Editor de Supabase
-- ==========================================

-- 1. TABLA CIE10 (Si no existe)
CREATE TABLE IF NOT EXISTS cie10 (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    descripcion TEXT NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    sexo_aplicable VARCHAR(20) DEFAULT 'Ambos', -- Ambos, Masculino, Femenino
    edad_minima INTEGER DEFAULT 0,
    edad_maxima INTEGER DEFAULT 120
);

-- 2. TABLA USERS (Usuarios del sistema)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('admin', 'medico', 'cajero')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    active BOOLEAN DEFAULT true
);

-- 3. TABLA CITAS (Agendamiento)
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT REFERENCES pacientes(id_paciente) ON DELETE CASCADE,
    medico_id BIGINT REFERENCES users(id) ON DELETE SET NULL, 
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    duracion_minutos INTEGER DEFAULT 30,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'atendida', 'cancelada')),
    motivo_consulta TEXT,
    motivo_cancelacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- ÍNDICES Y SEGURIDAD
-- ==========================================

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_citas_paciente ON citas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_citas_medico ON citas(medico_id);
CREATE INDEX IF NOT EXISTS idx_citas_fecha ON citas(fecha_hora);
CREATE INDEX IF NOT EXISTS idx_cie10_search ON cie10(codigo, descripcion);

-- Habilitar Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE citas ENABLE ROW LEVEL SECURITY;
ALTER TABLE cie10 ENABLE ROW LEVEL SECURITY;

-- Políticas de Acceso (Permitir lectura/escritura a la API)
-- Nota: Usamos "IF NOT EXISTS" conceptualmente borrando políticas previas si fallan, 
-- pero Supabase no soporta "CREATE POLICY IF NOT EXISTS" nativamente en todas las versiones.
-- Lo más seguro es intentar crearlas. Si ya existen, dará error, IGNORA ese error específico.

DO $$ 
BEGIN
    -- Política Users
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'users' AND policyname = 'Permitir todo en users') THEN
        CREATE POLICY "Permitir todo en users" ON users FOR ALL USING (true);
    END IF;

    -- Política Citas
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'citas' AND policyname = 'Permitir todo en citas') THEN
        CREATE POLICY "Permitir todo en citas" ON citas FOR ALL USING (true);
    END IF;

    -- Política CIE10
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'cie10' AND policyname = 'Permitir lectura cie10') THEN
        CREATE POLICY "Permitir lectura cie10" ON cie10 FOR SELECT USING (true);
    END IF;
END $$;
